import { Router } from 'express'
import { z } from 'zod'
import { prisma } from '../config/prisma'
import { authenticate } from '../middleware/authenticate'
import { authorize, canAccessAgency, canAccessBranch, tenantScope } from '../middleware/authorize'
import { hashPassword } from '../modules/auth/auth.service'

const router = Router()
router.use(authenticate, tenantScope)
const agencyInput = z.object({ name: z.string().min(2), legalName: z.string().optional(), email: z.string().email(), phone: z.string().optional(), address: z.string().optional(), city: z.string().optional(), country: z.string().default('Gabon') })
const branchInput = z.object({ agencyId: z.string().min(1), name: z.string().min(2), code: z.string().min(1).max(20), address: z.string().optional(), city: z.string().optional(), phone: z.string().optional(), email: z.string().email().optional() })
const branchPatch = branchInput.omit({ agencyId: true }).partial().extend({ status: z.enum(['ACTIVE', 'INACTIVE']).optional() })
const userInput = z.object({ agencyId: z.string().nullable().optional(), branchId: z.string().nullable().optional(), roleId: z.string(), firstName: z.string().min(1), lastName: z.string().min(1), email: z.string().email(), phone: z.string().optional(), password: z.string().min(8) })
const userPatch = userInput.partial().omit({ password: true }).extend({ status: z.enum(['ACTIVE', 'INACTIVE', 'SUSPENDED']).optional() })
const audit = (userId: string, action: string, entity: string, entityId: string, scope: { agencyId?: string | null; branchId?: string | null } = {}) => prisma.auditLog.create({ data: { userId, action, entity, entityId, agencyId: scope.agencyId ?? null, branchId: scope.branchId ?? null } })

router.get('/agencies', authorize('agency:read'), async (req, res, next) => { try { const data = await prisma.agency.findMany({ where: req.scope?.agencyId ? { id: req.scope.agencyId } : undefined, include: { _count: { select: { branches: true, users: true } } }, orderBy: { createdAt: 'desc' } }); res.json(data) } catch (e) { next(e) } })
router.post('/agencies', authorize('agency:create'), async (req, res, next) => { try { if (req.identity!.role !== 'SUPER_ADMIN') return res.status(403).json({ error: 'FORBIDDEN' }); const data = await prisma.agency.create({ data: agencyInput.parse(req.body) }); await audit(req.identity!.userId, 'AGENCY_CREATED', 'Agency', data.id, { agencyId: data.id }); res.status(201).json(data) } catch (e) { next(e) } })
router.get('/agencies/:id', authorize('agency:read'), async (req, res, next) => { try { const id = String(req.params.id); if (!canAccessAgency(req, id)) return res.status(403).json({ error: 'FORBIDDEN' }); const data = await prisma.agency.findUnique({ where: { id }, include: { branches: true, _count: { select: { users: true } } } }); if (!data) return res.status(404).json({ error: 'NOT_FOUND' }); res.json(data) } catch (e) { next(e) } })
router.patch('/agencies/:id', authorize('agency:update'), async (req, res, next) => { try { const id = String(req.params.id); if (!canAccessAgency(req, id)) return res.status(403).json({ error: 'FORBIDDEN' }); const data = await prisma.agency.update({ where: { id }, data: agencyInput.partial().extend({ status: z.enum(['ACTIVE', 'SUSPENDED', 'INACTIVE']).optional() }).parse(req.body) }); await audit(req.identity!.userId, 'AGENCY_UPDATED', 'Agency', data.id, { agencyId: data.id }); res.json(data) } catch (e) { next(e) } })

router.get('/branches', authorize('branch:read'), async (req, res, next) => { try { const data = await prisma.branch.findMany({ where: req.scope?.branchId ? { id: req.scope.branchId } : req.scope?.agencyId ? { agencyId: req.scope.agencyId } : undefined, orderBy: { name: 'asc' } }); res.json(data) } catch (e) { next(e) } })
router.get('/branches/:id', authorize('branch:read'), async (req, res, next) => { try { const id = String(req.params.id); const branch = await prisma.branch.findUnique({ where: { id } }); if (!branch) return res.status(404).json({ error: 'NOT_FOUND' }); if (!canAccessBranch(req, id, branch.agencyId)) return res.status(403).json({ error: 'FORBIDDEN' }); res.json(branch) } catch (e) { next(e) } })
router.post('/branches', authorize('branch:create'), async (req, res, next) => { try { const input = branchInput.parse(req.body); if (!canAccessAgency(req, input.agencyId)) return res.status(403).json({ error: 'FORBIDDEN' }); const agency = await prisma.agency.findUnique({ where: { id: input.agencyId } }); if (!agency) return res.status(404).json({ error: 'AGENCY_NOT_FOUND' }); const data = await prisma.branch.create({ data: input }); await audit(req.identity!.userId, 'BRANCH_CREATED', 'Branch', data.id, { agencyId: data.agencyId, branchId: data.id }); res.status(201).json(data) } catch (e) { next(e) } })
router.patch('/branches/:id', authorize('branch:update'), async (req, res, next) => { try { const id = String(req.params.id); const current = await prisma.branch.findUnique({ where: { id } }); if (!current) return res.status(404).json({ error: 'NOT_FOUND' }); if (!canAccessBranch(req, id, current.agencyId)) return res.status(403).json({ error: 'FORBIDDEN' }); const data = await prisma.branch.update({ where: { id }, data: branchPatch.parse(req.body) }); await audit(req.identity!.userId, 'BRANCH_UPDATED', 'Branch', data.id, { agencyId: data.agencyId, branchId: data.id }); res.json(data) } catch (e) { next(e) } })

router.get('/users', authorize('user:read'), async (req, res, next) => { try { const data = await prisma.user.findMany({ where: req.scope?.branchId ? { branchId: req.scope.branchId } : req.scope?.agencyId ? { agencyId: req.scope.agencyId } : undefined, select: { id: true, agencyId: true, branchId: true, roleId: true, firstName: true, lastName: true, email: true, phone: true, status: true, lastLoginAt: true, createdAt: true, role: true }, orderBy: { createdAt: 'desc' } }); res.json(data) } catch (e) { next(e) } })
router.get('/users/:id', authorize('user:read'), async (req, res, next) => { try { const id = String(req.params.id); const data = await prisma.user.findUnique({ where: { id }, select: { id: true, agencyId: true, branchId: true, roleId: true, firstName: true, lastName: true, email: true, phone: true, status: true, lastLoginAt: true, createdAt: true, role: true } }); if (!data) return res.status(404).json({ error: 'NOT_FOUND' }); if (!canAccessAgency(req, data.agencyId ?? '') || (req.scope?.branchId && data.branchId !== req.scope.branchId)) return res.status(403).json({ error: 'FORBIDDEN' }); res.json(data) } catch (e) { next(e) } })
router.post('/users', authorize('user:create'), async (req, res, next) => { try { const input = userInput.parse(req.body); if (input.agencyId && !canAccessAgency(req, input.agencyId)) return res.status(403).json({ error: 'FORBIDDEN' }); if (input.branchId && !canAccessBranch(req, input.branchId, input.agencyId ?? undefined)) return res.status(403).json({ error: 'FORBIDDEN' }); if (input.branchId) { const branch = await prisma.branch.findUnique({ where: { id: input.branchId } }); if (!branch || branch.agencyId !== input.agencyId) return res.status(422).json({ error: 'BRANCH_AGENCY_MISMATCH' }) } const role = await prisma.role.findUnique({ where: { id: input.roleId } }); if (!role || (req.identity!.role !== 'SUPER_ADMIN' && role.systemRole === 'SUPER_ADMIN')) return res.status(403).json({ error: 'FORBIDDEN' }); const { password, ...safeInput } = input; const data = await prisma.user.create({ data: { ...safeInput, email: input.email.toLowerCase(), passwordHash: await hashPassword(password) } }); await audit(req.identity!.userId, 'USER_CREATED', 'User', data.id, { agencyId: data.agencyId, branchId: data.branchId }); res.status(201).json({ id: data.id, email: data.email }) } catch (e) { next(e) } })
router.patch('/users/:id', authorize('user:update'), async (req, res, next) => { try { const id = String(req.params.id); const current = await prisma.user.findUnique({ where: { id }, include: { role: true } }); if (!current) return res.status(404).json({ error: 'NOT_FOUND' }); if (!canAccessAgency(req, current.agencyId ?? '') || (req.scope?.branchId && current.branchId !== req.scope.branchId)) return res.status(403).json({ error: 'FORBIDDEN' }); const input = userPatch.parse(req.body); if (input.roleId && input.roleId !== current.roleId && current.id === req.identity!.userId) return res.status(403).json({ error: 'SELF_ROLE_CHANGE_FORBIDDEN' }); if (input.roleId) { const role = await prisma.role.findUnique({ where: { id: input.roleId } }); if (!role || (role.systemRole === 'SUPER_ADMIN' && req.identity!.role !== 'SUPER_ADMIN')) return res.status(403).json({ error: 'FORBIDDEN' }) } if (input.agencyId && !canAccessAgency(req, input.agencyId)) return res.status(403).json({ error: 'FORBIDDEN' }); if (input.branchId && !canAccessBranch(req, input.branchId, input.agencyId ?? current.agencyId ?? undefined)) return res.status(403).json({ error: 'FORBIDDEN' }); const data = await prisma.user.update({ where: { id }, data: { ...input, email: input.email?.toLowerCase() } }); await audit(req.identity!.userId, input.roleId && input.roleId !== current.roleId ? 'USER_ROLE_CHANGED' : 'USER_UPDATED', 'User', data.id, { agencyId: data.agencyId, branchId: data.branchId }); res.json({ id: data.id, status: data.status }) } catch (e) { next(e) } })
router.get('/audit', authorize('audit:read'), async (req, res, next) => { try { const data = await prisma.auditLog.findMany({ where: req.scope?.branchId ? { branchId: req.scope.branchId } : req.scope?.agencyId ? { agencyId: req.scope.agencyId } : undefined, orderBy: { createdAt: 'desc' }, take: 100 }); res.json(data) } catch (e) { next(e) } })
router.get('/roles', authorize('role:read'), async (_req, res, next) => { try { res.json(await prisma.role.findMany({ include: { permissions: { include: { permission: true } } }, orderBy: { name: 'asc' } })) } catch (error) { next(error) } })
router.get('/permissions', authorize('permission:read'), async (_req, res, next) => { try { res.json(await prisma.permission.findMany({ orderBy: { code: 'asc' } })) } catch (error) { next(error) } })

export { router as foundationRouter }
