import { Router } from 'express'
import { z } from 'zod'
import { prisma } from '../../config/prisma'
import { authenticate } from '../../middleware/authenticate'
import { authorize, canAccessAgency, canAccessBranch, tenantScope } from '../../middleware/authorize'

const router = Router()
router.use(authenticate, tenantScope)
const type = z.enum(['BUS', 'MINIBUS', 'VAN', 'CAR', 'OTHER'])
const status = z.enum(['ACTIVE', 'INACTIVE', 'MAINTENANCE'])
const input = z.object({ agencyId: z.string().min(1), branchId: z.string().min(1), registrationNumber: z.string().trim().min(2).max(30), brand: z.string().trim().min(1).max(80), model: z.string().trim().min(1).max(80), year: z.coerce.number().int().min(1900).max(new Date().getFullYear() + 1), color: z.string().trim().max(40).optional(), vehicleType: type, seatCapacity: z.coerce.number().int().min(1).max(200), status: status }).strict()
const patch = input.partial().strict()
const audit = (userId: string, action: string, vehicle: { id: string; agencyId: string; branchId: string; registrationNumber: string }, metadata?: object) => prisma.auditLog.create({ data: { userId, action, entity: 'Vehicle', entityId: vehicle.id, agencyId: vehicle.agencyId, branchId: vehicle.branchId, metadata: { registrationNumber: vehicle.registrationNumber, ...metadata } } })
async function checkScope(req: any, agencyId: string, branchId: string) { if (!canAccessAgency(req, agencyId) || !canAccessBranch(req, branchId, agencyId)) return false; const branch = await prisma.branch.findUnique({ where: { id: branchId }, select: { agencyId: true } }); return Boolean(branch && branch.agencyId === agencyId) }

router.get('/', authorize('vehicle:read'), async (req, res, next) => { try { const query = z.object({ search: z.string().optional(), status: status.optional(), vehicleType: type.optional(), agencyId: z.string().optional(), branchId: z.string().optional(), page: z.coerce.number().int().min(1).default(1), pageSize: z.coerce.number().int().min(1).max(100).default(20) }).parse(req.query); const scopeWhere: Record<string, string> = req.scope?.branchId ? { branchId: req.scope.branchId } : req.scope?.agencyId ? { agencyId: req.scope.agencyId } : {}; const requestedScope = query.branchId ? { branchId: query.branchId } : query.agencyId ? { agencyId: query.agencyId } : {}; if (requestedScope.agencyId && scopeWhere.agencyId && requestedScope.agencyId !== scopeWhere.agencyId) return res.status(403).json({ error: 'FORBIDDEN' }); if (requestedScope.branchId && scopeWhere.branchId && requestedScope.branchId !== scopeWhere.branchId) return res.status(403).json({ error: 'FORBIDDEN' }); if (requestedScope.branchId && scopeWhere.agencyId) { const branch = await prisma.branch.findUnique({ where: { id: requestedScope.branchId }, select: { agencyId: true } }); if (!branch || branch.agencyId !== scopeWhere.agencyId) return res.status(403).json({ error: 'FORBIDDEN' }); } const where: any = { ...scopeWhere, ...(requestedScope.branchId || requestedScope.agencyId ? requestedScope : {}), ...(query.status ? { status: query.status } : {}), ...(query.vehicleType ? { vehicleType: query.vehicleType } : {}), ...(query.search ? { OR: [{ registrationNumber: { contains: query.search, mode: 'insensitive' } }, { brand: { contains: query.search, mode: 'insensitive' } }, { model: { contains: query.search, mode: 'insensitive' } }] } : {}) }; const [items, total] = await prisma.$transaction([prisma.vehicle.findMany({ where, include: { agency: { select: { id: true, name: true } }, branch: { select: { id: true, name: true, code: true } } }, orderBy: { createdAt: 'desc' }, skip: (query.page - 1) * query.pageSize, take: query.pageSize }), prisma.vehicle.count({ where })]); res.json({ items, page: query.page, pageSize: query.pageSize, total }) } catch (e) { next(e) } })
router.get('/:id', authorize('vehicle:read'), async (req, res, next) => { try { const item = await prisma.vehicle.findUnique({ where: { id: String(req.params.id) }, include: { branch: true } }); if (!item) return res.status(404).json({ error: 'NOT_FOUND' }); if (!await checkScope(req, item.agencyId, item.branchId)) return res.status(403).json({ error: 'FORBIDDEN' }); res.json(item) } catch (e) { next(e) } })
router.post('/', authorize('vehicle:create'), async (req, res, next) => { try { const data = input.parse(req.body); if (!await checkScope(req, data.agencyId, data.branchId)) return res.status(403).json({ error: 'FORBIDDEN' }); const item = await prisma.vehicle.create({ data }); await audit(req.identity!.userId, 'CREATE_VEHICLE', item); res.status(201).json(item) } catch (e) { next(e) } })
router.patch('/:id', authorize('vehicle:update'), async (req, res, next) => { try { const current = await prisma.vehicle.findUnique({ where: { id: String(req.params.id) } }); if (!current) return res.status(404).json({ error: 'NOT_FOUND' }); if (!await checkScope(req, current.agencyId, current.branchId)) return res.status(403).json({ error: 'FORBIDDEN' }); const data = patch.parse(req.body); const agencyId = data.agencyId ?? current.agencyId; const branchId = data.branchId ?? current.branchId; if (!await checkScope(req, agencyId, branchId)) return res.status(403).json({ error: 'FORBIDDEN' }); const item = await prisma.vehicle.update({ where: { id: current.id }, data }); await audit(req.identity!.userId, 'UPDATE_VEHICLE', item, { changed: Object.keys(data) }); res.json(item) } catch (e) { next(e) } })
router.delete('/:id', authorize('vehicle:delete'), async (req, res, next) => { try { const item = await prisma.vehicle.findUnique({ where: { id: String(req.params.id) } }); if (!item) return res.status(404).json({ error: 'NOT_FOUND' }); if (!await checkScope(req, item.agencyId, item.branchId)) return res.status(403).json({ error: 'FORBIDDEN' }); await audit(req.identity!.userId, 'DELETE_VEHICLE', item); await prisma.vehicle.delete({ where: { id: item.id } }); res.status(204).send() } catch (e) { next(e) } })
export { router as vehiclesRouter }
